//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_AddressPic
    {
        public long AddPicId { get; set; }
        public Nullable<int> AddId { get; set; }
        public string PicURL { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string blob { get; set; }
    }
}
