//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_APIRequest
    {
        public long Entryid { get; set; }
        public Nullable<bool> Revenue { get; set; }
        public Nullable<bool> Cost { get; set; }
        public Nullable<bool> Attendance { get; set; }
        public Nullable<bool> GPS { get; set; }
        public Nullable<bool> OrderInfo { get; set; }
        public Nullable<bool> VehicleInfo { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
