//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_AttachmentMaster
    {
        public long AttachmentId { get; set; }
        public string AttachmentType { get; set; }
        public string Attachment { get; set; }
        public Nullable<int> PersonTypeId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
    }
}
