//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Address
    {
        public DB_Address()
        {
            this.DB_Client = new HashSet<DB_Client>();
            this.db_LogisurePoint = new HashSet<db_LogisurePoint>();
            this.DB_Depot = new HashSet<DB_Depot>();
            this.DB_DepotStation = new HashSet<DB_DepotStation>();
            this.DB_Helper = new HashSet<DB_Helper>();
            this.DB_Helper1 = new HashSet<DB_Helper>();
            this.DB_Organisation = new HashSet<DB_Organisation>();
            this.DB_Vehicle_ParkingAddress = new HashSet<DB_Vehicle_ParkingAddress>();
        }
    
        public long AddressId { get; set; }
        public string PlotNo { get; set; }
        public string StreetName { get; set; }
        public string Area { get; set; }
        public string Landmark { get; set; }
        public string PinCode { get; set; }
        public Nullable<short> CityId { get; set; }
        public Nullable<short> StateId { get; set; }
        public string FullAddress { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string HindiAddress { get; set; }
        public string Relatedto { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public Nullable<short> pointStrength { get; set; }
    
        public virtual ICollection<DB_Client> DB_Client { get; set; }
        public virtual ICollection<db_LogisurePoint> db_LogisurePoint { get; set; }
        public virtual DB_City DB_City { get; set; }
        public virtual DB_States DB_States { get; set; }
        public virtual ICollection<DB_Depot> DB_Depot { get; set; }
        public virtual ICollection<DB_DepotStation> DB_DepotStation { get; set; }
        public virtual ICollection<DB_Helper> DB_Helper { get; set; }
        public virtual ICollection<DB_Helper> DB_Helper1 { get; set; }
        public virtual ICollection<DB_Organisation> DB_Organisation { get; set; }
        public virtual ICollection<DB_Vehicle_ParkingAddress> DB_Vehicle_ParkingAddress { get; set; }
    }
}
