//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Bill_Discount
    {
        public long DiscountId { get; set; }
        public Nullable<long> BillId { get; set; }
        public string DiscountType { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public string DiscountReason { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
    }
}
