//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_BillingInfo
    {
        public DB_BillingInfo()
        {
            this.DB_Bill_Charges = new HashSet<DB_Bill_Charges>();
        }
    
        public long BillingId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Segment { get; set; }
        public Nullable<System.DateTime> StatementFromDate { get; set; }
        public Nullable<System.DateTime> StatementToDate { get; set; }
        public Nullable<System.DateTime> PayByDate { get; set; }
        public string TariffPlan { get; set; }
        public string StatementNumber { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
        public string StatementPerson { get; set; }
        public string StatementEmail { get; set; }
        public Nullable<int> NoOfManagedDeliveries { get; set; }
        public Nullable<int> NoOfVansUsed { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public Nullable<int> BillGeneratedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedOn { get; set; }
    
        public virtual ICollection<DB_Bill_Charges> DB_Bill_Charges { get; set; }
    }
}
