//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Bill_Charges
    {
        public long BillChargesId { get; set; }
        public Nullable<long> BillingId { get; set; }
        public Nullable<double> VasCharges { get; set; }
        public Nullable<double> AdvCharges { get; set; }
        public Nullable<double> PromoCharges { get; set; }
        public Nullable<double> SpecSerCharges { get; set; }
        public Nullable<double> TollTaxCharges { get; set; }
        public Nullable<double> TotalUsageCharges { get; set; }
        public Nullable<double> TotalCurentPeriodCharges { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual DB_BillingInfo DB_BillingInfo { get; set; }
    }
}
