//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_BookingTypeMaster
    {
        public DB_BookingTypeMaster()
        {
            this.DB_ClientBookingTypeMapping = new HashSet<DB_ClientBookingTypeMapping>();
        }
    
        public int BookingTypeId { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<DB_ClientBookingTypeMapping> DB_ClientBookingTypeMapping { get; set; }
    }
}
