//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_ClientServiceType
    {
        public DB_ClientServiceType()
        {
            this.DB_ClientServiceTypeMapping = new HashSet<DB_ClientServiceTypeMapping>();
        }
    
        public int ClientServiceTypeId { get; set; }
        public string ServiceTypeName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<DB_ClientServiceTypeMapping> DB_ClientServiceTypeMapping { get; set; }
    }
}
