//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_CustomUserProfile
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> PasswordFailureSinceLastSucess { get; set; }
        public Nullable<System.DateTime> PasswordChangeDate { get; set; }
        public Nullable<long> PersonID { get; set; }
        public Nullable<int> PersonTypeID { get; set; }
        public string Email { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string PhoneNo { get; set; }
        public string CityOfOperation { get; set; }
        public string FullName { get; set; }
        public Nullable<int> AccessToRole { get; set; }
        public string Permissions { get; set; }
        public string AccessToModule { get; set; }
    }
}
