//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_ClientBookingTypeMapping
    {
        public int Id { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<short> PersonTypeId { get; set; }
        public Nullable<int> BookingTypeId { get; set; }
        public Nullable<System.DateTime> BookingStartDate { get; set; }
        public Nullable<System.DateTime> BookingLastDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
    
        public virtual DB_BookingTypeMaster DB_BookingTypeMaster { get; set; }
    }
}
