//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Client
    {
        public DB_Client()
        {
            this.DB_Depot = new HashSet<DB_Depot>();
            this.DB_ItemRegistration = new HashSet<DB_ItemRegistration>();
            this.DB_Order_Details = new HashSet<DB_Order_Details>();
            this.DB_Order_Details1 = new HashSet<DB_Order_Details>();
            this.DB_DepotStation = new HashSet<DB_DepotStation>();
            this.DB_mainOrders = new HashSet<DB_mainOrders>();
            this.DB_mainOrders1 = new HashSet<DB_mainOrders>();
        }
    
        public long ClientId { get; set; }
        public long OrganisationId { get; set; }
        public string ClientName { get; set; }
        public int ClientReferredTypeId { get; set; }
        public string ClientReferredBy { get; set; }
        public Nullable<int> ClientInitatedById { get; set; }
        public Nullable<int> ClientBusinessActivityTypeId { get; set; }
        public Nullable<int> ClientProductTypeId { get; set; }
        public string ProductBrandRemark { get; set; }
        public Nullable<int> ExpectedTripsPerMonthId { get; set; }
        public Nullable<int> MaterialTypeId { get; set; }
        public Nullable<System.DateTime> ExpectedBusinessStartDate { get; set; }
        public Nullable<bool> IsTGSRequired { get; set; }
        public string BusinessStartTime { get; set; }
        public string BusinessEndTime { get; set; }
        public string Email_Id { get; set; }
        public Nullable<long> AddressId { get; set; }
        public string UserId { get; set; }
        public string ClientNameInHindi { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ClientCode { get; set; }
        public Nullable<bool> IsProspected { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public string BlockedRemarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> LinkActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string MACaddress { get; set; }
        public string Website { get; set; }
        public string ProspectiveApprovedBy { get; set; }
        public string FinalApprovedBy { get; set; }
        public Nullable<bool> IsSMSService { get; set; }
        public Nullable<bool> IsPhotoAllowed { get; set; }
        public Nullable<bool> IsNextDaysAttendanceRequired { get; set; }
        public Nullable<bool> IsPersonDetailsRequired { get; set; }
        public Nullable<int> NoOfPhotographs { get; set; }
        public Nullable<bool> IsClientDetailsNumberRequired { get; set; }
        public Nullable<bool> IsSignatureRequired { get; set; }
        public Nullable<bool> IsScheduledOrder { get; set; }
        public Nullable<bool> IsCDNPermission { get; set; }
        public Nullable<System.DateTime> ExpectedTGSStartDate { get; set; }
        public Nullable<System.DateTime> ExpectedTGSEndDate { get; set; }
        public string SOPE { get; set; }
        public Nullable<int> PayableDays { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string PaymentMode { get; set; }
        public string BillingTaxNo { get; set; }
        public Nullable<short> BillingCycleID { get; set; }
    
        public virtual DB_Address DB_Address { get; set; }
        public virtual DB_InitiatedPerson DB_InitiatedPerson { get; set; }
        public virtual DB_ClientBusinessActivityType DB_ClientBusinessActivityType { get; set; }
        public virtual DB_ClientProductType DB_ClientProductType { get; set; }
        public virtual DB_ClientReferredType DB_ClientReferredType { get; set; }
        public virtual DB_ExpectedTripsPerMonth DB_ExpectedTripsPerMonth { get; set; }
        public virtual DB_MaterialType DB_MaterialType { get; set; }
        public virtual DB_Organisation DB_Organisation { get; set; }
        public virtual ICollection<DB_Depot> DB_Depot { get; set; }
        public virtual ICollection<DB_ItemRegistration> DB_ItemRegistration { get; set; }
        public virtual ICollection<DB_Order_Details> DB_Order_Details { get; set; }
        public virtual ICollection<DB_Order_Details> DB_Order_Details1 { get; set; }
        public virtual ICollection<DB_DepotStation> DB_DepotStation { get; set; }
        public virtual ICollection<DB_mainOrders> DB_mainOrders { get; set; }
        public virtual ICollection<DB_mainOrders> DB_mainOrders1 { get; set; }
        public virtual DB_PaymentCycle DB_PaymentCycle { get; set; }
    }
}
