//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_CcenterTest
    {
        public int CCTest_Id { get; set; }
        public string FromNum { get; set; }
        public string ToNum { get; set; }
        public string CMessage { get; set; }
        public string CallSid { get; set; }
        public string Direction { get; set; }
        public string DialCallDuration { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string CallType { get; set; }
        public string DialWhomNumber { get; set; }
        public string digits { get; set; }
        public Nullable<bool> IsCallFetched { get; set; }
        public string Snooze { get; set; }
        public string Bot { get; set; }
        public string CallFrom { get; set; }
        public string CallTo { get; set; }
        public string Created { get; set; }
        public string CallStatus { get; set; }
        public string AgentEmail { get; set; }
        public string RecordingAvailableBy { get; set; }
    }
}
