//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_ClientVehicleMapping
    {
        public int ID { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<long> VehicleTypeId { get; set; }
    }
}
