//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_CcallSummary
    {
        public int CallSumId { get; set; }
        public string CallSid { get; set; }
        public string CallFrom { get; set; }
        public string CallTo { get; set; }
        public string CallStatus { get; set; }
        public string Direction { get; set; }
        public string ForwardedFrom { get; set; }
        public string Created { get; set; }
        public string DialCallDuration { get; set; }
        public string RecordingUrl { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string DialCallStatus { get; set; }
        public string CallType { get; set; }
        public string DialWhomNumber { get; set; }
        public string flow_id { get; set; }
        public string tenant_id { get; set; }
        public string RecordingAvailableBy { get; set; }
        public string GroupName { get; set; }
        public string CsFrom { get; set; }
        public string GetUrl { get; set; }
        public string CsTo { get; set; }
    }
}
