//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_ClientServiceTypeMapping
    {
        public int MappingId { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
    
        public virtual DB_ClientServiceType DB_ClientServiceType { get; set; }
    }
}
