//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_ContactInformation
    {
        public long ContactId { get; set; }
        public string Number { get; set; }
        public string ContactPerson { get; set; }
        public string PersonDesignation { get; set; }
        public string Type { get; set; }
        public Nullable<int> PersonTypeId { get; set; }
        public Nullable<long> PersonId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public Nullable<bool> SMSService { get; set; }
    }
}
