//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_DepotStation
    {
        public DB_DepotStation()
        {
            this.DB_OrderDetails = new HashSet<DB_OrderDetails>();
            this.DB_OrderDetails1 = new HashSet<DB_OrderDetails>();
            this.DB_mainOrders = new HashSet<DB_mainOrders>();
        }
    
        public int DepotStationId { get; set; }
        public Nullable<long> ClientId { get; set; }
        public string Name { get; set; }
        public Nullable<long> AddressId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public string HindiName { get; set; }
        public string IPAddress { get; set; }
        public string Route { get; set; }
        public Nullable<bool> Verified { get; set; }
        public string MACAddress { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public string DepotStation { get; set; }
        public Nullable<bool> IsSMS { get; set; }
        public string BranchId { get; set; }
        public Nullable<int> LogisurePoint { get; set; }
        public Nullable<bool> IsTranshipmentPoint { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual DB_Address DB_Address { get; set; }
        public virtual DB_Client DB_Client { get; set; }
        public virtual db_LogisurePoint db_LogisurePoint { get; set; }
        public virtual ICollection<DB_OrderDetails> DB_OrderDetails { get; set; }
        public virtual ICollection<DB_OrderDetails> DB_OrderDetails1 { get; set; }
        public virtual ICollection<DB_mainOrders> DB_mainOrders { get; set; }
    }
}
