//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Driver
    {
        public DB_Driver()
        {
            this.DB_Vehicle_Tracking = new HashSet<DB_Vehicle_Tracking>();
            this.DB_VehicleAssetMappingLog = new HashSet<DB_VehicleAssetMappingLog>();
        }
    
        public int DriverId { get; set; }
        public string DriverName { get; set; }
        public string FullAddress { get; set; }
        public Nullable<bool> IsPoliceVerification { get; set; }
        public string PoliceVerificationRemark { get; set; }
        public Nullable<int> UdanDriverId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<short> CityId { get; set; }
        public Nullable<short> StateId { get; set; }
        public string BankName { get; set; }
        public string BankAccountNo { get; set; }
        public string BankBranchName { get; set; }
        public string PhoneNumber { get; set; }
        public string PhotoUrl { get; set; }
        public string IFSC_CODE { get; set; }
    
        public virtual DB_City DB_City { get; set; }
        public virtual DB_States DB_States { get; set; }
        public virtual ICollection<DB_Vehicle_Tracking> DB_Vehicle_Tracking { get; set; }
        public virtual ICollection<DB_VehicleAssetMappingLog> DB_VehicleAssetMappingLog { get; set; }
    }
}
