//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Depot
    {
        public DB_Depot()
        {
            this.DB_OrderItems = new HashSet<DB_OrderItems>();
        }
    
        public int DepotId { get; set; }
        public Nullable<bool> Verified { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string DepotName { get; set; }
        public string HindiDepotName { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<long> AddressId { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsSMS { get; set; }
        public string BranchId { get; set; }
    
        public virtual DB_Address DB_Address { get; set; }
        public virtual DB_Client DB_Client { get; set; }
        public virtual ICollection<DB_OrderItems> DB_OrderItems { get; set; }
    }
}
