//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_EcomResponseCode
    {
        public int EcomResponseCodeId { get; set; }
        public string Pincode { get; set; }
        public string ProblemCode { get; set; }
        public string MandatoryComment { get; set; }
        public string category { get; set; }
        public string ProblemDescription { get; set; }
        public string LogisureCode { get; set; }
    }
}
