//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_EndCallInfo
    {
        public int EndCall_Id { get; set; }
        public string CallSid { get; set; }
        public string EcFrom { get; set; }
        public string EcTo { get; set; }
        public string DialCallDuration { get; set; }
        public string Direction { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string CallType { get; set; }
        public string DialWhomNumber { get; set; }
        public string digits { get; set; }
    }
}
