//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_EODDetails
    {
        public int Id { get; set; }
        public string Fromm { get; set; }
        public string Too { get; set; }
        public string CCC { get; set; }
        public string Task { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string AttatchmentURL { get; set; }
        public string Remarks { get; set; }
    }
}
