//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_EcomIntegrationData
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNumber { get; set; }
        public string FullAddress { get; set; }
        public string TrackingID { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<double> COD { get; set; }
        public string Status { get; set; }
        public string Pincode { get; set; }
        public string BranchId { get; set; }
        public string Weight { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string ProductType { get; set; }
        public string PCS { get; set; }
        public string runsheetname { get; set; }
        public string Services { get; set; }
        public Nullable<System.DateTime> PickUpDate { get; set; }
        public string BillingAccountNumber { get; set; }
        public string ShipperNumber { get; set; }
        public string ShipperName { get; set; }
        public string SentBy { get; set; }
        public string ShipperAddress { get; set; }
        public string ShipperTelephone { get; set; }
        public string Comments { get; set; }
        public string ShipperEmail { get; set; }
        public string ConsigneeReference2 { get; set; }
        public string ConsigneeEmail { get; set; }
        public string CommodityDescription { get; set; }
        public string AttentionOf { get; set; }
        public string RouteCode { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<bool> iscancelby { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> indstdtime { get; set; }
        public string username { get; set; }
        public string HAWBDestinationEntity { get; set; }
    }
}
