//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_FareStructure_WeightWise
    {
        public int ID { get; set; }
        public Nullable<decimal> ThresholdWeight { get; set; }
        public Nullable<decimal> ThresholdCharge { get; set; }
        public Nullable<int> FareStrucutureID { get; set; }
        public Nullable<decimal> ExtraPerKgRate { get; set; }
        public Nullable<decimal> MinQty { get; set; }
    
        public virtual DB_FareStructure DB_FareStructure { get; set; }
    }
}
