//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_FareStructure
    {
        public DB_FareStructure()
        {
            this.DB_FareStructure_DestinationWise = new HashSet<DB_FareStructure_DestinationWise>();
            this.DB_FareStructure_WeightWise = new HashSet<DB_FareStructure_WeightWise>();
        }
    
        public int FareStructureID { get; set; }
        public Nullable<int> TariffPlan { get; set; }
        public Nullable<int> PersonTypeID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<short> BillingCycleID { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<int> LoadingTime { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<int> PayableDays { get; set; }
        public Nullable<decimal> Charges1 { get; set; }
        public Nullable<decimal> Charges2 { get; set; }
        public Nullable<decimal> ClientCharges2After { get; set; }
        public Nullable<decimal> MinCharges { get; set; }
        public Nullable<decimal> MinQty { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string IPAddress { get; set; }
        public string OrderType { get; set; }
        public string BillingTaxNo { get; set; }
        public Nullable<bool> IsConvenienceChargesPresent { get; set; }
        public string ConvenienceChargesAfter { get; set; }
        public string ConvenienceChargesBefore { get; set; }
        public Nullable<decimal> ConvenienceCharges { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> ThresholdKM { get; set; }
        public Nullable<double> ExtraKMCharges { get; set; }
        public Nullable<double> MonthlyFixedCharges { get; set; }
        public Nullable<int> WorkingDays { get; set; }
        public string DayMonthKm { get; set; }
        public string MaxDailyHours { get; set; }
        public Nullable<double> ExtraMinuteCost { get; set; }
        public Nullable<bool> ChampionAllowed { get; set; }
        public Nullable<double> ChampionCharges { get; set; }
        public Nullable<double> BaseFare { get; set; }
        public Nullable<bool> IsReturnBase { get; set; }
        public Nullable<double> ReturnBaseFare { get; set; }
        public Nullable<short> VehicleTypeId { get; set; }
        public Nullable<int> Helper { get; set; }
    
        public virtual DB_PaymentCycle DB_PaymentCycle { get; set; }
        public virtual ICollection<DB_FareStructure_DestinationWise> DB_FareStructure_DestinationWise { get; set; }
        public virtual ICollection<DB_FareStructure_WeightWise> DB_FareStructure_WeightWise { get; set; }
        public virtual DB_VehicleType DB_VehicleType { get; set; }
    }
}
