//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_FareStructure_DestinationWise
    {
        public int ID { get; set; }
        public Nullable<int> FromPersonTypeId { get; set; }
        public Nullable<int> FromPersonId { get; set; }
        public Nullable<int> ToPersonTypeId { get; set; }
        public Nullable<int> ToPersonId { get; set; }
        public Nullable<int> FareStrucutureID { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public Nullable<decimal> AdditionalPointCharge { get; set; }
    
        public virtual DB_FareStructure DB_FareStructure { get; set; }
    }
}
