//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_GPS
    {
        public DB_GPS()
        {
            this.DB_Vehicle_Tracking = new HashSet<DB_Vehicle_Tracking>();
        }
    
        public int GPSId { get; set; }
        public string GPSNo { get; set; }
        public string PurchasedFrom { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> PurchasedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Status { get; set; }
        public Nullable<short> CityId { get; set; }
        public Nullable<short> StateId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public string Remark { get; set; }
        public string LogiCode { get; set; }
    
        public virtual DB_City DB_City { get; set; }
        public virtual DB_States DB_States { get; set; }
        public virtual ICollection<DB_Vehicle_Tracking> DB_Vehicle_Tracking { get; set; }
    }
}
