//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_GeonLogin
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string MobileNo { get; set; }
        public string ExecutiveName { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
