//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_HelperDailyAttedance
    {
        public long AttendanceId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longtitude { get; set; }
        public Nullable<double> Accuracy { get; set; }
        public Nullable<long> HelperId { get; set; }
        public string PhotoURL { get; set; }
        public string DeviceId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string AttendanceType { get; set; }
        public string FullAddress { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public Nullable<double> MobileLat { get; set; }
        public Nullable<double> MobileLng { get; set; }
        public string MobileFullAddress { get; set; }
        public Nullable<System.DateTime> Indianstdtime { get; set; }
    }
}
