//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_ItemRegistration
    {
        public DB_ItemRegistration()
        {
            this.DB_OrderItems = new HashSet<DB_OrderItems>();
        }
    
        public int ItemId { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<bool> RackNeeded { get; set; }
        public Nullable<int> RackId { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> Length { get; set; }
        public string LengthUnit { get; set; }
        public Nullable<double> Width { get; set; }
        public string WidthUnit { get; set; }
        public Nullable<double> Height { get; set; }
        public string HeightUnit { get; set; }
        public Nullable<double> CFT { get; set; }
        public Nullable<bool> Fragile { get; set; }
        public Nullable<double> CapacityPerItem { get; set; }
        public string CapacityUnit { get; set; }
        public Nullable<short> PaymentBasisId { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual DB_Client DB_Client { get; set; }
        public virtual DB_PaymentBasis DB_PaymentBasis { get; set; }
        public virtual ICollection<DB_OrderItems> DB_OrderItems { get; set; }
    }
}
