//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_InitiatedPerson
    {
        public DB_InitiatedPerson()
        {
            this.DB_Client = new HashSet<DB_Client>();
            this.DB_Organisation = new HashSet<DB_Organisation>();
        }
    
        public int InitiatedId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public string Designation { get; set; }
    
        public virtual ICollection<DB_Client> DB_Client { get; set; }
        public virtual ICollection<DB_Organisation> DB_Organisation { get; set; }
    }
}
