//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_InternalSwPermissions
    {
        public DB_InternalSwPermissions()
        {
            this.DB_User_InternalPermissions = new HashSet<DB_User_InternalPermissions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<DB_User_InternalPermissions> DB_User_InternalPermissions { get; set; }
    }
}
