//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_JustSentSms
    {
        public int JsSms_Id { get; set; }
        public string AccountSid { get; set; }
        public string JsSid { get; set; }
        public string JsFrom { get; set; }
        public string JsTo { get; set; }
        public string DateCreated { get; set; }
        public string DateUpdated { get; set; }
        public string DateSent { get; set; }
        public string Body { get; set; }
        public string Direction { get; set; }
        public string Uri { get; set; }
        public string ApiVersion { get; set; }
        public string Price { get; set; }
        public string smsStatus { get; set; }
    }
}
