//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_LogisurePoint
    {
        public db_LogisurePoint()
        {
            this.DB_DepotStation = new HashSet<DB_DepotStation>();
            this.DB_Vehicle_ParkingAddress = new HashSet<DB_Vehicle_ParkingAddress>();
        }
    
        public int LPid { get; set; }
        public string LPName { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<long> addressid { get; set; }
    
        public virtual DB_Address DB_Address { get; set; }
        public virtual ICollection<DB_DepotStation> DB_DepotStation { get; set; }
        public virtual ICollection<DB_Vehicle_ParkingAddress> DB_Vehicle_ParkingAddress { get; set; }
    }
}
