//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_LogiMember
    {
        public int LogiMemberID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PresentEmail { get; set; }
        public string DesiredEmail { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CityOfOperation { get; set; }
        public string AccessToModule { get; set; }
        public Nullable<int> AccessToRole { get; set; }
        public string Permissions { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual DB_LogiMember DB_LogiMember1 { get; set; }
        public virtual DB_LogiMember DB_LogiMember2 { get; set; }
    }
}
