//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_LSVehicle
    {
        public DB_LSVehicle()
        {
            this.DB_Vehicle_ParkingAddress = new HashSet<DB_Vehicle_ParkingAddress>();
            this.DB_VehicleDailyAttendance = new HashSet<DB_VehicleDailyAttendance>();
            this.DB_VehicleMonthlyBillingReport = new HashSet<DB_VehicleMonthlyBillingReport>();
            this.DB_Vehicle_Tracking = new HashSet<DB_Vehicle_Tracking>();
            this.DB_VehiclePenalty = new HashSet<DB_VehiclePenalty>();
            this.DB_VehicleAssetMappingLog = new HashSet<DB_VehicleAssetMappingLog>();
            this.DB_ExtraCharge = new HashSet<DB_ExtraCharge>();
            this.DB_Deduction = new HashSet<DB_Deduction>();
        }
    
        public long LS_VehicleId { get; set; }
        public string VehicleNo { get; set; }
        public string UDId { get; set; }
        public Nullable<int> UDVehicleId { get; set; }
        public Nullable<short> StateId { get; set; }
        public Nullable<short> CityId { get; set; }
        public string GPSNo { get; set; }
        public Nullable<bool> IsMonthlyFixed { get; set; }
        public Nullable<int> RateForFullDay { get; set; }
        public Nullable<int> RateForHalfDay { get; set; }
        public Nullable<int> PaidHoliday { get; set; }
        public Nullable<int> CommittedKM { get; set; }
        public Nullable<int> MonthlyFixedAmount { get; set; }
        public Nullable<int> RateForExtraKM { get; set; }
        public string MonthlyFixedType { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string TerminationReason { get; set; }
        public string NoDuesSatatusBy_Finance { get; set; }
        public string NoDuesSatatusBy_Operation { get; set; }
        public Nullable<System.DateTime> ServiceAvailableDate { get; set; }
        public Nullable<int> LsFleetownerId { get; set; }
        public string ServiceType { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string MACAddress { get; set; }
        public string ApproverRemark { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<bool> IsLinkUsed { get; set; }
        public Nullable<double> NoOfHours { get; set; }
        public string VehicleType { get; set; }
        public Nullable<double> FuelEfficency { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public Nullable<System.DateTime> DateOfTermination { get; set; }
        public Nullable<bool> VehiclePoliceVerStatus { get; set; }
        public string PoliceVerRemark { get; set; }
        public string LSID { get; set; }
        public Nullable<short> Logivehicletypeid { get; set; }
        public Nullable<bool> Recreated { get; set; }
        public string ClientIDs { get; set; }
        public string PlanID { get; set; }
        public string referral_code { get; set; }
    
        public virtual DB_City DB_City { get; set; }
        public virtual DB_LSFleetOwner DB_LSFleetOwner { get; set; }
        public virtual DB_States DB_States { get; set; }
        public virtual ICollection<DB_Vehicle_ParkingAddress> DB_Vehicle_ParkingAddress { get; set; }
        public virtual ICollection<DB_VehicleDailyAttendance> DB_VehicleDailyAttendance { get; set; }
        public virtual ICollection<DB_VehicleMonthlyBillingReport> DB_VehicleMonthlyBillingReport { get; set; }
        public virtual DB_VehicleType DB_VehicleType { get; set; }
        public virtual ICollection<DB_Vehicle_Tracking> DB_Vehicle_Tracking { get; set; }
        public virtual ICollection<DB_VehiclePenalty> DB_VehiclePenalty { get; set; }
        public virtual ICollection<DB_VehicleAssetMappingLog> DB_VehicleAssetMappingLog { get; set; }
        public virtual ICollection<DB_ExtraCharge> DB_ExtraCharge { get; set; }
        public virtual ICollection<DB_Deduction> DB_Deduction { get; set; }
    }
}
