//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_mainOrders
    {
        public DB_mainOrders()
        {
            this.DB_mainOrderLog = new HashSet<DB_mainOrderLog>();
            this.DB_OrderDetails = new HashSet<DB_OrderDetails>();
        }
    
        public long OrderId { get; set; }
        public string CRNNumber { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> AssignedAt { get; set; }
        public string AssignedBy { get; set; }
        public string Remarks { get; set; }
        public string Vehicle { get; set; }
        public string Status { get; set; }
        public string OrderType { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public string Route { get; set; }
        public string IsCancelBy { get; set; }
        public Nullable<double> OrderKm { get; set; }
        public string OrderCompletedBy { get; set; }
        public Nullable<double> OrderRevenueAmount { get; set; }
        public Nullable<double> ConvenienceCharges { get; set; }
        public Nullable<bool> ForceRevenueGenerate { get; set; }
        public string BillNo { get; set; }
        public Nullable<double> MailSnoozeTime { get; set; }
        public Nullable<int> NoOfHelper { get; set; }
        public Nullable<short> VehicleTypeID { get; set; }
        public Nullable<double> ApproxWeight { get; set; }
        public Nullable<int> DepotStationId { get; set; }
        public string ServiceType { get; set; }
        public Nullable<System.DateTime> EstimatedPickupTime { get; set; }
        public Nullable<decimal> OrderWeight { get; set; }
        public Nullable<double> distanceAP { get; set; }
        public Nullable<decimal> EnrouteExpenses { get; set; }
        public Nullable<double> TripTime { get; set; }
        public Nullable<bool> isconfirmed { get; set; }
        public Nullable<bool> Feedback { get; set; }
        public string EstimatedFare { get; set; }
        public string EstimatedTime { get; set; }
        public string EstimatedKM { get; set; }
        public Nullable<double> Discount { get; set; }
        public string FareFrom { get; set; }
        public Nullable<int> ApproxLoadingUnloadingTime { get; set; }
        public Nullable<short> ClientTypeId { get; set; }
        public string HelperName { get; set; }
        public string referral_code { get; set; }
        public Nullable<double> orderhirecharge { get; set; }
    
        public virtual DB_Client DB_Client { get; set; }
        public virtual DB_Client DB_Client1 { get; set; }
        public virtual DB_DepotStation DB_DepotStation { get; set; }
        public virtual ICollection<DB_mainOrderLog> DB_mainOrderLog { get; set; }
        public virtual DB_VehicleType DB_VehicleType { get; set; }
        public virtual ICollection<DB_OrderDetails> DB_OrderDetails { get; set; }
        public virtual DB_VehicleType DB_VehicleType1 { get; set; }
    }
}
