//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_OtherOrdersLog
    {
        public long UID { get; set; }
        public Nullable<int> CreatedOrderId { get; set; }
        public Nullable<int> RefOrderId { get; set; }
        public Nullable<System.DateTime> CreatedAtTimeStamp { get; set; }
        public string CreatedAtPlace { get; set; }
        public Nullable<double> CreatedAtLatitude { get; set; }
        public Nullable<double> CreatedAtLongitude { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedAccuracy { get; set; }
        public Nullable<double> GpsLat { get; set; }
        public Nullable<double> GpsLng { get; set; }
        public Nullable<System.DateTime> GpsDatetime { get; set; }
    }
}
