//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Order_Details_Audit
    {
        public int AUDITID { get; set; }
        public long UID { get; set; }
        public int OrderId { get; set; }
        public string Consignor { get; set; }
        public string PPhone { get; set; }
        public string PAddress { get; set; }
        public Nullable<double> PLat { get; set; }
        public Nullable<double> PLng { get; set; }
        public Nullable<System.DateTime> PtimeLow { get; set; }
        public Nullable<System.DateTime> PtimeHigh { get; set; }
        public Nullable<decimal> PmaxLoad { get; set; }
        public Nullable<int> Pseq { get; set; }
        public Nullable<System.DateTime> PETA { get; set; }
        public string PDocument { get; set; }
        public Nullable<double> COP { get; set; }
        public Nullable<double> PCharges { get; set; }
        public string Consignee { get; set; }
        public string DPhone { get; set; }
        public string DAddress { get; set; }
        public Nullable<double> DLat { get; set; }
        public Nullable<double> DLng { get; set; }
        public Nullable<System.DateTime> DtimeLow { get; set; }
        public Nullable<System.DateTime> DtimeHigh { get; set; }
        public Nullable<decimal> DmaxLoad { get; set; }
        public Nullable<int> Dseq { get; set; }
        public Nullable<System.DateTime> DETA { get; set; }
        public string DDocument { get; set; }
        public Nullable<double> COD { get; set; }
        public Nullable<double> DCharges { get; set; }
        public Nullable<double> CFT { get; set; }
        public string Vehicle { get; set; }
        public string Status { get; set; }
        public string Instructions { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string PContactPerson { get; set; }
        public string DContactPerson { get; set; }
        public Nullable<bool> PAddressVerified { get; set; }
        public Nullable<bool> DAddressVerified { get; set; }
        public Nullable<bool> IsReschedule { get; set; }
        public string TakenFrom { get; set; }
        public string TakenFromName { get; set; }
        public string DeliveredTo { get; set; }
        public string DeliveredToName { get; set; }
        public Nullable<long> PClientId { get; set; }
        public string PUnitClass { get; set; }
        public Nullable<long> DClientId { get; set; }
        public Nullable<long> DUnitClass { get; set; }
        public string TodayAttendance { get; set; }
        public string DayAfterAttendance { get; set; }
        public Nullable<bool> HolidayOrNot { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public Nullable<System.DateTime> ReachedAt_Pickup { get; set; }
        public Nullable<System.DateTime> ReachedAt_Delivery { get; set; }
        public string ClubedId { get; set; }
        public Nullable<long> tripId { get; set; }
        public string ReverseKey { get; set; }
        public string OrderType { get; set; }
        public string IncrementalKm { get; set; }
        public string Route { get; set; }
        public Nullable<bool> IsCancelBy { get; set; }
        public Nullable<double> OrderKm { get; set; }
        public string OrderCompletedBy { get; set; }
        public string BillOrBiltyNum { get; set; }
        public Nullable<double> OrderRevenueAmount { get; set; }
        public Nullable<double> FairChargesAmount { get; set; }
        public Nullable<decimal> ConvenienceCharges { get; set; }
        public Nullable<decimal> ThresholdWtOrQty { get; set; }
        public Nullable<bool> ForceRevenueGenerate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> BillNo { get; set; }
        public Nullable<bool> IsLiftAvailable { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public Nullable<System.DateTime> MailSnoozeTime { get; set; }
        public Nullable<long> NoOfHelper { get; set; }
        public Nullable<long> VehicleTypeID { get; set; }
        public Nullable<decimal> ApproxWeight { get; set; }
        public string DistanceAP { get; set; }
        public string DistancePD { get; set; }
        public Nullable<double> OrderWeight { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> UpdatedOnIndstdtime { get; set; }
    }
}
