//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_OrderDeclined
    {
        public long DeclinedId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<long> DeclinedIMageId { get; set; }
        public string DeclinedReason { get; set; }
        public Nullable<double> DeclinedAtLat { get; set; }
        public Nullable<double> DeclinedAtLng { get; set; }
        public Nullable<double> DeclinedAtAccuracy { get; set; }
        public Nullable<System.DateTime> DeclinedAtTimeStamp { get; set; }
        public string DeclinedAtPlace { get; set; }
        public Nullable<double> GpsLat { get; set; }
        public Nullable<double> GpsLng { get; set; }
        public Nullable<System.DateTime> GpsDateTime { get; set; }
    
        public virtual DB_PhotoUpload DB_PhotoUpload { get; set; }
    }
}
