//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Organisation
    {
        public DB_Organisation()
        {
            this.DB_Client = new HashSet<DB_Client>();
        }
    
        public long OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public Nullable<short> OrganisationTypeId { get; set; }
        public Nullable<long> AddressId { get; set; }
        public string Email_Id { get; set; }
        public string Website { get; set; }
        public string PAN_Number { get; set; }
        public string GovtRegistrationNo { get; set; }
        public string Logo { get; set; }
        public Nullable<bool> CanUseLogo { get; set; }
        public Nullable<System.DateTime> RegisteredOn { get; set; }
        public Nullable<bool> Active { get; set; }
        public string OrganisationCode { get; set; }
        public string Headquarter { get; set; }
        public string OrganisationNameInHindi { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public Nullable<int> InitatedById { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public string BlockedRemarks { get; set; }
        public string FinalApprovedBy { get; set; }
        public string ProspectiveApprovedBy { get; set; }
    
        public virtual DB_Address DB_Address { get; set; }
        public virtual ICollection<DB_Client> DB_Client { get; set; }
        public virtual DB_InitiatedPerson DB_InitiatedPerson { get; set; }
        public virtual DB_Organisation DB_Organisation1 { get; set; }
        public virtual DB_Organisation DB_Organisation2 { get; set; }
        public virtual DB_OrganisationType DB_OrganisationType { get; set; }
    }
}
