//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Order_info
    {
        public long UId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<double> COD { get; set; }
        public Nullable<double> COP { get; set; }
        public Nullable<double> Pcharges { get; set; }
        public Nullable<double> Dcharges { get; set; }
        public string Instructions { get; set; }
        public string Psignature { get; set; }
        public string PTime { get; set; }
        public string Dsignature { get; set; }
        public string DTime { get; set; }
        public string Prate1 { get; set; }
        public string Pcomments { get; set; }
        public string Drate1 { get; set; }
        public string Dcomments { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string DeclinedReason { get; set; }
        public Nullable<double> FinalLat { get; set; }
        public Nullable<double> FinalLng { get; set; }
        public Nullable<double> PFLat { get; set; }
        public Nullable<double> PFLng { get; set; }
        public Nullable<double> DFLat { get; set; }
        public Nullable<double> DFLng { get; set; }
        public string TodayAttendence { get; set; }
        public string DayAfterAttendence { get; set; }
        public Nullable<bool> DayAfterHoliday { get; set; }
        public string ForceCompleteReason { get; set; }
        public string TripKM { get; set; }
        public string PFLatLngAccuracy { get; set; }
        public string DFLatLngAccuracy { get; set; }
        public string GoogleKM { get; set; }
        public Nullable<double> PGpsLat { get; set; }
        public Nullable<double> PGpsLng { get; set; }
        public Nullable<System.DateTime> PGpsDateTime { get; set; }
        public Nullable<double> DGpsLat { get; set; }
        public Nullable<double> DGpsLng { get; set; }
        public Nullable<System.DateTime> DGpsDateTime { get; set; }
    }
}
