//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_OrganisationType
    {
        public DB_OrganisationType()
        {
            this.DB_Organisation = new HashSet<DB_Organisation>();
        }
    
        public short OrgTypeId { get; set; }
        public string OrganisationType { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<DB_Organisation> DB_Organisation { get; set; }
    }
}
