//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_PhoneTracking
    {
        public long PhoneTrackingId { get; set; }
        public Nullable<int> PhoneId { get; set; }
        public Nullable<double> Accuracy { get; set; }
        public Nullable<double> Altitude { get; set; }
        public Nullable<double> AltitudeAccuracy { get; set; }
        public Nullable<double> Heading { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string PositionSource { get; set; }
        public string SatelliteData { get; set; }
        public Nullable<double> Speed { get; set; }
        public string Timestamp { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
