//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_PhotoUpload
    {
        public DB_PhotoUpload()
        {
            this.DB_OrderDeclined = new HashSet<DB_OrderDeclined>();
            this.DB_OrderLog = new HashSet<DB_OrderLog>();
            this.DB_OrderLog1 = new HashSet<DB_OrderLog>();
            this.DB_OrderLog2 = new HashSet<DB_OrderLog>();
        }
    
        public long PhotoId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string PhotoType { get; set; }
        public string PD { get; set; }
        public string PhotoURL { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string ImageURI { get; set; }
    
        public virtual ICollection<DB_OrderDeclined> DB_OrderDeclined { get; set; }
        public virtual ICollection<DB_OrderLog> DB_OrderLog { get; set; }
        public virtual ICollection<DB_OrderLog> DB_OrderLog1 { get; set; }
        public virtual ICollection<DB_OrderLog> DB_OrderLog2 { get; set; }
    }
}
