//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_PhoneInfo
    {
        public DB_PhoneInfo()
        {
            this.DB_Vehicle_Tracking = new HashSet<DB_Vehicle_Tracking>();
        }
    
        public int PhoneId { get; set; }
        public string PhoneNo { get; set; }
        public string IMEINo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> Price { get; set; }
        public string NetworkProvider { get; set; }
        public string PhoneType { get; set; }
        public Nullable<System.DateTime> PhonePurchaseDate { get; set; }
        public string PurchasedFrom { get; set; }
        public Nullable<bool> IsMobileTracker { get; set; }
        public Nullable<short> CityId { get; set; }
        public Nullable<short> StateId { get; set; }
        public string DeviceId { get; set; }
        public string LogiCode { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string MobileModel { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Modifiedby { get; set; }
        public string IPAddress { get; set; }
    
        public virtual DB_City DB_City { get; set; }
        public virtual ICollection<DB_Vehicle_Tracking> DB_Vehicle_Tracking { get; set; }
        public virtual DB_States DB_States { get; set; }
    }
}
