//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Penalty
    {
        public int Id { get; set; }
        public string Factor { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Charge { get; set; }
        public string Description { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string IPAddress { get; set; }
    
        public virtual DB_Penalty DB_Penalty1 { get; set; }
        public virtual DB_Penalty DB_Penalty2 { get; set; }
    }
}
