//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_SendSms
    {
        public int SendSms_Id { get; set; }
        public string SmsSid { get; set; }
        public string SmsStatus { get; set; }
        public string DateUpdated { get; set; }
        public string UrlBot { get; set; }
    }
}
