//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Spot_FareFactors
    {
        public int FareFactorsId { get; set; }
        public Nullable<double> OverheadCost { get; set; }
        public Nullable<double> Profit { get; set; }
        public Nullable<double> CoverForDiscount { get; set; }
        public Nullable<short> CityId { get; set; }
        public Nullable<double> FloorCharges { get; set; }
        public Nullable<decimal> BaseFare { get; set; }
    
        public virtual DB_City DB_City { get; set; }
    }
}
