//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_SPickupMDelivery
    {
        public long Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string PickDel { get; set; }
        public Nullable<System.DateTime> ReachedAt { get; set; }
        public Nullable<double> ReachedLat { get; set; }
        public Nullable<double> ReachedLng { get; set; }
        public string ReachedAtAccuracy { get; set; }
        public string ReachedAtPlotno { get; set; }
        public string ReachedAtRoadName { get; set; }
        public string ReachedAtArea { get; set; }
        public string ReachedAtCity { get; set; }
        public string ReachedAtState { get; set; }
        public string ReachedAtCountry { get; set; }
        public string ReachedAtPincode { get; set; }
        public string ReachedAtFormattedAddress { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> CashCollected { get; set; }
        public string Vehicle { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public Nullable<double> CompletedLat { get; set; }
        public Nullable<double> CompletedLng { get; set; }
        public string CompletedAccuracy { get; set; }
        public string CompletedPlotno { get; set; }
        public string CompletedRoadName { get; set; }
        public string CompletedArea { get; set; }
        public string CompletedCity { get; set; }
        public string CompletedState { get; set; }
        public string CompletedCountry { get; set; }
        public string CompletedPincode { get; set; }
        public string CompletedFormattedAddress { get; set; }
        public Nullable<long> PhotoId { get; set; }
        public Nullable<long> PhotoId2 { get; set; }
        public string Reason { get; set; }
        public string Signature { get; set; }
        public string BillOrBiltyNum { get; set; }
        public string PlaceName { get; set; }
        public Nullable<double> GpsLat { get; set; }
        public Nullable<double> GpsLng { get; set; }
        public Nullable<System.DateTime> GpsDateTime { get; set; }
    }
}
