//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Spot_HelperCharges
    {
        public int SpotHelperChargesID { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<int> WorkingDays { get; set; }
        public Nullable<double> WorkingMinute { get; set; }
        public Nullable<double> PerMinuteCharges { get; set; }
        public Nullable<short> NoofHleper { get; set; }
        public Nullable<double> CostPerDay { get; set; }
        public Nullable<double> HireChargesCostPerday { get; set; }
        public Nullable<double> HireChargesCostPerMinute { get; set; }
    }
}
