//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Spot_OrderDetails
    {
        public long OrderDetailsId { get; set; }
        public Nullable<long> SpotOrderId { get; set; }
        public Nullable<double> GPSLatitude { get; set; }
        public Nullable<double> GPSLongitude { get; set; }
        public Nullable<System.DateTime> GPSDatetime { get; set; }
        public string GPSAddress { get; set; }
        public string EventType { get; set; }
        public Nullable<System.DateTime> IndianStdTime { get; set; }
        public string DistanceTravelled { get; set; }
        public string PhotoUrl { get; set; }
        public string SignatureUrl { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> MobileLatitude { get; set; }
        public Nullable<double> MobileLongitude { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual DB_Spot_Orders DB_Spot_Orders { get; set; }
        public virtual DB_Spot_Orders DB_Spot_Orders1 { get; set; }
    }
}
