//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Vehicle_ParkingAddress
    {
        public int ParkingId { get; set; }
        public Nullable<long> AddressId { get; set; }
        public string AddressType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.TimeSpan> ParkingTime { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<long> LS_VehicleId { get; set; }
        public Nullable<int> LPid { get; set; }
    
        public virtual DB_Address DB_Address { get; set; }
        public virtual db_LogisurePoint db_LogisurePoint { get; set; }
        public virtual DB_LSVehicle DB_LSVehicle { get; set; }
    }
}
