//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_VehicleType
    {
        public DB_VehicleType()
        {
            this.DB_LSVehicle = new HashSet<DB_LSVehicle>();
            this.DB_mainOrders = new HashSet<DB_mainOrders>();
            this.DB_mainOrders1 = new HashSet<DB_mainOrders>();
            this.DB_FareStructure = new HashSet<DB_FareStructure>();
        }
    
        public short ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<DB_LSVehicle> DB_LSVehicle { get; set; }
        public virtual ICollection<DB_mainOrders> DB_mainOrders { get; set; }
        public virtual ICollection<DB_mainOrders> DB_mainOrders1 { get; set; }
        public virtual ICollection<DB_FareStructure> DB_FareStructure { get; set; }
    }
}
