//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_VehicleEnrouteExpenses
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Vehicle { get; set; }
        public Nullable<double> EnrouteExpenses { get; set; }
        public string billImageURL { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public string SubmittedFrom { get; set; }
        public string ChargeType { get; set; }
    
        public virtual DB_VehicleEnrouteExpenses DB_VehicleEnrouteExpenses1 { get; set; }
        public virtual DB_VehicleEnrouteExpenses DB_VehicleEnrouteExpenses2 { get; set; }
    }
}
