//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_VehicleMonthlyBillingReport
    {
        public int VMBRID { get; set; }
        public string VehicleType { get; set; }
        public string OwnerName { get; set; }
        public Nullable<System.DateTime> DateofMembership { get; set; }
        public Nullable<System.DateTime> DateofWithdrawal { get; set; }
        public Nullable<double> MBAperDay { get; set; }
        public Nullable<double> RateforExtraKm { get; set; }
        public Nullable<int> SundayOff { get; set; }
        public Nullable<int> NoofLeaves { get; set; }
        public Nullable<int> PayableDays { get; set; }
        public Nullable<double> TotalKmRun { get; set; }
        public Nullable<decimal> MBAAmountPayable { get; set; }
        public Nullable<decimal> Incentives { get; set; }
        public Nullable<decimal> Penalties { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public Nullable<decimal> EnrouteExpenses { get; set; }
        public Nullable<decimal> NetAmountPayable { get; set; }
        public string Remarks { get; set; }
        public string Month { get; set; }
        public Nullable<short> CityId { get; set; }
        public Nullable<decimal> SecurityDeposit { get; set; }
        public Nullable<decimal> MembershipAmount { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public Nullable<long> LS_VehicleId { get; set; }
        public string HireStructure { get; set; }
        public Nullable<double> Commmittedkm { get; set; }
        public Nullable<double> ExtraKm { get; set; }
        public Nullable<int> eligibleoff { get; set; }
        public Nullable<int> presentdays { get; set; }
    
        public virtual DB_LSVehicle DB_LSVehicle { get; set; }
    }
}
