//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Vehicle_TrackingLog
    {
        public long VLogID { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Heading { get; set; }
        public Nullable<double> Speed { get; set; }
        public Nullable<double> Accuracy { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string GPSno { get; set; }
        public string Odometer { get; set; }
    }
}
