//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Vehicle_Client_Exclusivity
    {
        public int ExclusivityId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    }
}
