//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Vehicle_CaptiveFleet
    {
        public int UID { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<int> Unitid { get; set; }
        public string Route { get; set; }
    }
}
