//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_VehicleDailyAttendance
    {
        public long AttendanceId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longtitude { get; set; }
        public Nullable<double> Accuracy { get; set; }
        public string PhotoURL { get; set; }
        public string DeviceId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string AttendanceType { get; set; }
        public string FullAddress { get; set; }
        public Nullable<double> DistanceFromParkingAddress { get; set; }
        public Nullable<double> GPSKm { get; set; }
        public Nullable<double> LogbookReading { get; set; }
        public Nullable<double> MobileAppKm { get; set; }
        public Nullable<double> ReceivedDataUsage { get; set; }
        public Nullable<double> SentDataUsage { get; set; }
        public Nullable<decimal> DieselRate { get; set; }
        public string PersonType { get; set; }
        public Nullable<bool> MorningOk { get; set; }
        public Nullable<bool> EveningOk { get; set; }
        public Nullable<double> ToPayKM { get; set; }
        public Nullable<double> DieselPayment { get; set; }
        public Nullable<double> MobileLat { get; set; }
        public Nullable<double> MobileLng { get; set; }
        public Nullable<System.DateTime> IndianStdtime { get; set; }
        public string Remark { get; set; }
        public Nullable<long> LS_VehicleId { get; set; }
        public Nullable<double> DutyTime { get; set; }
        public Nullable<double> Odometer { get; set; }
        public Nullable<System.DateTime> GPSdatetime { get; set; }
        public string PresentAbsent { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> AbsentType { get; set; }
        public Nullable<double> Distlptoamp { get; set; }
        public Nullable<double> Distletoamp { get; set; }
        public string AppVersioninfo { get; set; }
        public Nullable<double> HireCharges { get; set; }
        public string dphccreatedby { get; set; }
        public string Remarkfordp { get; set; }
        public Nullable<double> SuggestedKM { get; set; }
        public Nullable<bool> ISverified { get; set; }
        public string verifiedby { get; set; }
        public Nullable<System.DateTime> verifiedat { get; set; }
    
        public virtual DB_LSVehicle DB_LSVehicle { get; set; }
    }
}
