//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_WebSitePageHit
    {
        public long Id { get; set; }
        public string PageName { get; set; }
        public Nullable<System.DateTime> HitTime { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public string UrlReferrer { get; set; }
        public string Source { get; set; }
    }
}
