//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogisureEntities1 : DbContext
    {
        public LogisureEntities1()
            : base("name=LogisureEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DB_Address> DB_Address { get; set; }
        public virtual DbSet<DB_AddressPic> DB_AddressPic { get; set; }
        public virtual DbSet<DB_APIRequest> DB_APIRequest { get; set; }
        public virtual DbSet<DB_AttachmentMaster> DB_AttachmentMaster { get; set; }
        public virtual DbSet<DB_Bill_Discount> DB_Bill_Discount { get; set; }
        public virtual DbSet<DB_BookingTypeMaster> DB_BookingTypeMaster { get; set; }
        public virtual DbSet<DB_CallCenterMapping> DB_CallCenterMapping { get; set; }
        public virtual DbSet<DB_CcenterTest> DB_CcenterTest { get; set; }
        public virtual DbSet<DB_City> DB_City { get; set; }
        public virtual DbSet<DB_Client> DB_Client { get; set; }
        public virtual DbSet<DB_ClientBookingTypeMapping> DB_ClientBookingTypeMapping { get; set; }
        public virtual DbSet<DB_ClientBusinessActivityType> DB_ClientBusinessActivityType { get; set; }
        public virtual DbSet<DB_ClientProductType> DB_ClientProductType { get; set; }
        public virtual DbSet<DB_ClientReferredType> DB_ClientReferredType { get; set; }
        public virtual DbSet<DB_ClientServiceType> DB_ClientServiceType { get; set; }
        public virtual DbSet<DB_ClientServiceTypeMapping> DB_ClientServiceTypeMapping { get; set; }
        public virtual DbSet<DB_ClientTurnAroundTime> DB_ClientTurnAroundTime { get; set; }
        public virtual DbSet<DB_ClientVehicleMapping> DB_ClientVehicleMapping { get; set; }
        public virtual DbSet<DB_ContactInformation> DB_ContactInformation { get; set; }
        public virtual DbSet<DB_Dapp_Login> DB_Dapp_Login { get; set; }
        public virtual DbSet<DB_Depot> DB_Depot { get; set; }
        public virtual DbSet<DB_DepotStation> DB_DepotStation { get; set; }
        public virtual DbSet<DB_DocumentTypes> DB_DocumentTypes { get; set; }
        public virtual DbSet<DB_Driver> DB_Driver { get; set; }
        public virtual DbSet<DB_EcomIntegrationData> DB_EcomIntegrationData { get; set; }
        public virtual DbSet<DB_EcomResponseCode> DB_EcomResponseCode { get; set; }
        public virtual DbSet<DB_EODDetails> DB_EODDetails { get; set; }
        public virtual DbSet<DB_EODLogin> DB_EODLogin { get; set; }
        public virtual DbSet<DB_ExpectedTripsPerMonth> DB_ExpectedTripsPerMonth { get; set; }
        public virtual DbSet<DB_FareStructure> DB_FareStructure { get; set; }
        public virtual DbSet<DB_FareStructure_DestinationWise> DB_FareStructure_DestinationWise { get; set; }
        public virtual DbSet<DB_FareStructure_WeightWise> DB_FareStructure_WeightWise { get; set; }
        public virtual DbSet<DB_GeonLogin> DB_GeonLogin { get; set; }
        public virtual DbSet<DB_GPS> DB_GPS { get; set; }
        public virtual DbSet<DB_Helper> DB_Helper { get; set; }
        public virtual DbSet<DB_HelperDailyAttedance> DB_HelperDailyAttedance { get; set; }
        public virtual DbSet<DB_InitiatedPerson> DB_InitiatedPerson { get; set; }
        public virtual DbSet<DB_InternalSwPermissions> DB_InternalSwPermissions { get; set; }
        public virtual DbSet<DB_IPAddress> DB_IPAddress { get; set; }
        public virtual DbSet<DB_ItemRegistration> DB_ItemRegistration { get; set; }
        public virtual DbSet<DB_JustSentSms> DB_JustSentSms { get; set; }
        public virtual DbSet<DB_LogEverything> DB_LogEverything { get; set; }
        public virtual DbSet<db_LogisurePoint> db_LogisurePoint { get; set; }
        public virtual DbSet<DB_LSFleetOwner> DB_LSFleetOwner { get; set; }
        public virtual DbSet<DB_LSVehicle> DB_LSVehicle { get; set; }
        public virtual DbSet<DB_mainOrderLog> DB_mainOrderLog { get; set; }
        public virtual DbSet<DB_MarketVehicles> DB_MarketVehicles { get; set; }
        public virtual DbSet<DB_MaterialType> DB_MaterialType { get; set; }
        public virtual DbSet<DB_Order_Details> DB_Order_Details { get; set; }
        public virtual DbSet<DB_Order_Details_Audit> DB_Order_Details_Audit { get; set; }
        public virtual DbSet<DB_Order_info> DB_Order_info { get; set; }
        public virtual DbSet<DB_OrderDeclined> DB_OrderDeclined { get; set; }
        public virtual DbSet<DB_OrderDetails> DB_OrderDetails { get; set; }
        public virtual DbSet<DB_OrderItems> DB_OrderItems { get; set; }
        public virtual DbSet<DB_OrderLog> DB_OrderLog { get; set; }
        public virtual DbSet<DB_OrderLog_Audit> DB_OrderLog_Audit { get; set; }
        public virtual DbSet<DB_Orders> DB_Orders { get; set; }
        public virtual DbSet<DB_Organisation> DB_Organisation { get; set; }
        public virtual DbSet<DB_OrganisationType> DB_OrganisationType { get; set; }
        public virtual DbSet<DB_OtherOrdersLog> DB_OtherOrdersLog { get; set; }
        public virtual DbSet<DB_ParkingAddress> DB_ParkingAddress { get; set; }
        public virtual DbSet<DB_PaymentBasis> DB_PaymentBasis { get; set; }
        public virtual DbSet<DB_PaymentCycle> DB_PaymentCycle { get; set; }
        public virtual DbSet<DB_PenalityIncentiveReason> DB_PenalityIncentiveReason { get; set; }
        public virtual DbSet<DB_Penalty> DB_Penalty { get; set; }
        public virtual DbSet<DB_Permission> DB_Permission { get; set; }
        public virtual DbSet<DB_PersonType> DB_PersonType { get; set; }
        public virtual DbSet<DB_PhoneInfo> DB_PhoneInfo { get; set; }
        public virtual DbSet<DB_PhoneLog> DB_PhoneLog { get; set; }
        public virtual DbSet<DB_PhoneTracking> DB_PhoneTracking { get; set; }
        public virtual DbSet<DB_PhotoUpload> DB_PhotoUpload { get; set; }
        public virtual DbSet<DB_RefrencePerson> DB_RefrencePerson { get; set; }
        public virtual DbSet<DB_ServiceMailMapping> DB_ServiceMailMapping { get; set; }
        public virtual DbSet<DB_ServiceVehicleStatus> DB_ServiceVehicleStatus { get; set; }
        public virtual DbSet<DB_SPickupMDelivery> DB_SPickupMDelivery { get; set; }
        public virtual DbSet<DB_Spot_ClientType> DB_Spot_ClientType { get; set; }
        public virtual DbSet<DB_Spot_CustomerProfile> DB_Spot_CustomerProfile { get; set; }
        public virtual DbSet<DB_Spot_FareFactors> DB_Spot_FareFactors { get; set; }
        public virtual DbSet<DB_Spot_HelperCharges> DB_Spot_HelperCharges { get; set; }
        public virtual DbSet<DB_Spot_Invoice> DB_Spot_Invoice { get; set; }
        public virtual DbSet<DB_Spot_OrderDetails> DB_Spot_OrderDetails { get; set; }
        public virtual DbSet<DB_Spot_OrderPointsinfo> DB_Spot_OrderPointsinfo { get; set; }
        public virtual DbSet<DB_Spot_Orders> DB_Spot_Orders { get; set; }
        public virtual DbSet<DB_Spot_UserProfile> DB_Spot_UserProfile { get; set; }
        public virtual DbSet<DB_Spot_VehicleFareCharges> DB_Spot_VehicleFareCharges { get; set; }
        public virtual DbSet<DB_States> DB_States { get; set; }
        public virtual DbSet<DB_TariffPlan> DB_TariffPlan { get; set; }
        public virtual DbSet<DB_TripKM> DB_TripKM { get; set; }
        public virtual DbSet<DB_User_InternalPermissions> DB_User_InternalPermissions { get; set; }
        public virtual DbSet<DB_UserIPMapping> DB_UserIPMapping { get; set; }
        public virtual DbSet<DB_UserPermission> DB_UserPermission { get; set; }
        public virtual DbSet<DB_UserProfile> DB_UserProfile { get; set; }
        public virtual DbSet<DB_UserRoles> DB_UserRoles { get; set; }
        public virtual DbSet<DB_UserToDepotMapping> DB_UserToDepotMapping { get; set; }
        public virtual DbSet<DB_UserToUnitMapping> DB_UserToUnitMapping { get; set; }
        public virtual DbSet<DB_Vehicle_City_Mapping> DB_Vehicle_City_Mapping { get; set; }
        public virtual DbSet<DB_Vehicle_Client_Exclusivity> DB_Vehicle_Client_Exclusivity { get; set; }
        public virtual DbSet<DB_Vehicle_Tracking> DB_Vehicle_Tracking { get; set; }
        public virtual DbSet<DB_Vehicle_TrackingLog> DB_Vehicle_TrackingLog { get; set; }
        public virtual DbSet<DB_VehicleAssetMappingLog> DB_VehicleAssetMappingLog { get; set; }
        public virtual DbSet<DB_VehicleDailyAttendance> DB_VehicleDailyAttendance { get; set; }
        public virtual DbSet<DB_VehicleEnrouteExpenses> DB_VehicleEnrouteExpenses { get; set; }
        public virtual DbSet<DB_VehicleMonthlyBillingReport> DB_VehicleMonthlyBillingReport { get; set; }
        public virtual DbSet<DB_VehiclePenalty> DB_VehiclePenalty { get; set; }
        public virtual DbSet<DB_VehicleRankingForUnit> DB_VehicleRankingForUnit { get; set; }
        public virtual DbSet<DB_VehicleType> DB_VehicleType { get; set; }
        public virtual DbSet<DB_WebSitePageHit> DB_WebSitePageHit { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
        public virtual DbSet<DB_Amt_Received> DB_Amt_Received { get; set; }
        public virtual DbSet<DB_Bill_Charges> DB_Bill_Charges { get; set; }
        public virtual DbSet<DB_BillingInfo> DB_BillingInfo { get; set; }
        public virtual DbSet<DB_BillPrintHistory> DB_BillPrintHistory { get; set; }
        public virtual DbSet<DB_CcallSummary> DB_CcallSummary { get; set; }
        public virtual DbSet<DB_Email_visitweb> DB_Email_visitweb { get; set; }
        public virtual DbSet<DB_LogisureBillingInfo> DB_LogisureBillingInfo { get; set; }
        public virtual DbSet<DB_SendSms> DB_SendSms { get; set; }
        public virtual DbSet<DB_Speed> DB_Speed { get; set; }
        public virtual DbSet<DB_Vehicle_CaptiveFleet> DB_Vehicle_CaptiveFleet { get; set; }
        public virtual DbSet<DB_Vehicle_ParkingAddress> DB_Vehicle_ParkingAddress { get; set; }
        public virtual DbSet<DB_WebsiteMetaInfo> DB_WebsiteMetaInfo { get; set; }
        public virtual DbSet<DB_EndCallInfo> DB_EndCallInfo { get; set; }
        public virtual DbSet<DB_UnitToAssociateStationUnitMapping> DB_UnitToAssociateStationUnitMapping { get; set; }
        public virtual DbSet<DB_VCAR_Login> DB_VCAR_Login { get; set; }
        public virtual DbSet<DB_GlobalSetting> DB_GlobalSetting { get; set; }
        public virtual DbSet<DB_mainOrders> DB_mainOrders { get; set; }
        public virtual DbSet<DB_ExtraCharge> DB_ExtraCharge { get; set; }
        public virtual DbSet<DB_Deduction> DB_Deduction { get; set; }
        public virtual DbSet<DB_CustomModules> DB_CustomModules { get; set; }
        public virtual DbSet<DB_CustomPermissions> DB_CustomPermissions { get; set; }
        public virtual DbSet<DB_CustomRole> DB_CustomRole { get; set; }
        public virtual DbSet<DB_CustomUserProfile> DB_CustomUserProfile { get; set; }
        public virtual DbSet<DB_LogiMember> DB_LogiMember { get; set; }
    }
}
