//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.DB_CallCenterMapping = new HashSet<DB_CallCenterMapping>();
            this.DB_UserIPMapping = new HashSet<DB_UserIPMapping>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string PassKey { get; set; }
    
        public virtual ICollection<DB_CallCenterMapping> DB_CallCenterMapping { get; set; }
        public virtual ICollection<DB_UserIPMapping> DB_UserIPMapping { get; set; }
    }
}
